export const currencies = [
  { code: "USD", name: "The United States Dollar" },
  { code: "EUR", name: "The Euro" },
  { code: "GBP", name: "The British Pound Sterling" },
  { code: "JPY", name: "The Japanese Yen" },
  { code: "AUD", name: "The Australian Dollar" },
  { code: "CAD", name: "The Canadian Dollar" },
  { code: "CHF", name: "The Swiss Franc" },
  { code: "CNY", name: "The Chinese Yuan" },
  { code: "INR", name: "The Indian Rupee" },
  { code: "RUB", name: "The Russian Ruble" },
  { code: "BRL", name: "The Brazilian Real" },
  { code: "ZAR", name: "The South African Rand" },
  { code: "MXN", name: "The Mexican Peso" },
  { code: "SGD", name: "The Singapore Dollar" },
  { code: "NZD", name: "The New Zealand Dollar" },
  { code: "HKD", name: "The Hong Kong Dollar" },
  { code: "AZN", name: "The Azerbaijani Manat" },
  { code: "BSD", name: "The Bahamian Dollar" },
  { code: "BBD", name: "The Barbados Dollar" },
  { code: "BYN", name: "The Belarus Ruble" },
];
